### ISSUE TITLE
Rendered HTML contains unclosed HTML-comment

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#113] opened 2017-06-06 11:34 UTC
This issue is likely related to #100, as its fix to incrementally parse HTML-blocks will probably also fix the following issue:

If some markdown text contains a multiline HTML-comment with a blank line in it, the renderer only renders the HTML-comment opening tag, while it escapes the comment-closing tag.

Example markdown:

```
<br>
<!--
comment

-->
This text gets rendered within an unclosed html comment
```

Rendered HTML:
```html
<!--
comment
<p>&ndash;&gt; This is rendered within an unclosed html comment</p>
```

[Example in babelmark 2](https://johnmacfarlane.net/babelmark2/?text=%3Cbr%3E%0A%3C!--%0Acomment%0A%0A--%3E%0AThis+is+rendered+within+an+unclosed+html+comment)

The more serious issue here is that the rendered HTML code will break the rest of the page, as the rest of page's HTML (up to an HTML-comment close tag) will become part of the (unclosed) HTML-comment. In one of our apps, this issue even caused the save-button to disappear, so one could not edit and save the problematic markdown text anymore without fixing the DOM clientside :laughing:.

We currently fix this by adding `<!--end-->` at the end of each rendered markdown.

**Comment by vsch** [comment] 2017-06-16 21:52
@Elmervc, this is caused by not parsing the HTML in an HTML block.

**Comment by vsch** [comment] 2017-07-12 22:30
@Elmervc, added features to make HTML block parsing better. Set `Parser.HTML_BLOCK_DEEP_PARSER` to true in your options. This is most compatible with CommonMark but handles raw tags not being on first line. The rest allow more tweaks. 

  * `Parser.HTML_BLOCK_DEEP_PARSER` default `false` - enable deep HTML block parsing
  * `Parser.HTML_BLOCK_DEEP_PARSE_NON_BLOCK` default 'true', parse non-block tags inside HTML
    blocks
  * `Parser.HTML_BLOCK_DEEP_PARSE_BLANK_LINE_INTERRUPTS` default `true`, when true Blank line
    interrupts HTML block when not in raw tag, otherwise only when closed
  * `Parser.HTML_BLOCK_DEEP_PARSE_MARKDOWN_INTERRUPTS_CLOSED` default false, when true Other
    markdown elements can interrupt a closed HTML block without an intervening blank line
  * `Parser.HTML_BLOCK_DEEP_PARSE_BLANK_LINE_INTERRUPTS_PARTIAL_TAG` default true, when true
    blank line interrupts partially open tag ie. `<TAG` without a corresponding `>` and having a
    blank line before `>`

**Comment by vsch** [comment] 2017-07-12 22:33
@Elmervc, didn't realize you are using pegdown compatibility. There is no need to do anything extra. By default the settings are adjusted for maximum pegdown compatibility. Unclosed HTML tags will continue to end of file looking for closing `>`.

Here are settings used for pegdown:

                    // deep HTML parsing for pegdown compatibility
                    .set(Parser.HTML_BLOCK_DEEP_PARSER, true)
                    .set(Parser.HTML_BLOCK_DEEP_PARSE_NON_BLOCK, true)
                    .set(Parser.HTML_BLOCK_DEEP_PARSE_BLANK_LINE_INTERRUPTS, false)
                    .set(Parser.HTML_BLOCK_DEEP_PARSE_MARKDOWN_INTERRUPTS_CLOSED, true)
                    .set(Parser.HTML_BLOCK_DEEP_PARSE_BLANK_LINE_INTERRUPTS_PARTIAL_TAG, false)

**Closed** 2017-07-14 19:59 UTC
Labels: bug, fixed :)
