### ISSUE TITLE
Tasklist display issue

### ISSUE THREAD

**Issue by rkanumola** [vsch/flexmark-java#136] opened 2017-08-01 14:01 UTC
@vsch , 
Our customer is giving the following input and looking for expected output.
```
Task List
- [x] Task 1
- [ ] Task 2
- [x] Task 3
```
**Flexmark Output**
![currentoutputusing flexmark](https://user-images.githubusercontent.com/28949740/28828857-a6d7551e-76ef-11e7-820d-f225f0edd969.png)

**Expected**
![customer expectation](https://user-images.githubusercontent.com/28949740/28828861-aabf34f8-76ef-11e7-8a01-b8ba22b68e73.jpg)

Can you suggest us why the output is not matching with the customer expectation?

**Comment by vsch** [comment] 2017-08-01 23:21
@rkanumola, default parsing and rendering should produce:

```html
<p>Task List</p>
<ul>
  <li>[x] Task 1</li>
  <li>[ ] Task 2</li>
  <li>[x] Task 3</li>
</ul>
```

Your output shows that the task complete marker is being rendered as a defined ref link . This means that either you have a definition `[x]: some.url` or your custom link resolver is resolving a reference with id `x` when it is not defined.

To have the correct output as your client expects you need to include the `flexmark-ext-gfm-tasklist` module with `TaskListExtension` included. By default the extension will render task list items using a disabled check box. See: https://github.com/vsch/flexmark-java/wiki/Extensions#gfm-tasklist

Then default rendering will be:

```html
<p>Task List</p>
<ul>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" checked="checked" disabled="disabled" readonly="readonly" />&nbsp;Task 1</li>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" disabled="disabled" readonly="readonly" />&nbsp;Task 2</li>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" checked="checked" disabled="disabled" readonly="readonly" />&nbsp;Task 3</li>
</ul>
```

And look like this:

![image](https://user-images.githubusercontent.com/10299086/28850785-a5d24fe6-76ec-11e7-9420-73eb2a558eca.png)

To get exact expected result you need to have the following markdown:

```markdown
# Task List
- [x] Task 1
- [ ] Task 2
- [x] Task 3
```

To get:

```html
<h1>Task List</h1>
<ul>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" checked="checked" disabled="disabled" readonly="readonly" />&nbsp;Task 1</li>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" disabled="disabled" readonly="readonly" />&nbsp;Task 2</li>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" checked="checked" disabled="disabled" readonly="readonly" />&nbsp;Task 3</li>
</ul>
```

![image](https://user-images.githubusercontent.com/10299086/28851113-86c26ff8-76ee-11e7-8706-3251c2589894.png)

**Comment by rkanumola** [comment] 2017-08-02 07:19
Thanks for the prompt response @vsch !!. 
We will follow your suggestion of using `flexmark-ext-gfm-tasklist` module and `TaskListExtension`  class And get back to you if we need any help.

**Comment by rkanumola** [comment] 2017-08-23 06:57
@vsch , I tried as per your suggestion and found that your guess mentioned below is correct that we are using ConfluenceWikiLinkRenderer which we have addressed with your suggestions on https://github.com/vsch/flexmark-java/issues/105. 

> Your output shows that the task complete marker is being rendered as a defined ref link . This means that either you have a definition [x]: some.url or your custom link resolver is resolving a reference with id x when it is not defined.

When I debug this sample data along with **flexmark-ext-gfm-tasklist** module and **TaskListExtension** debugger is going to ConfluenceWikiLinkRenderer custom resolver. Implementation is below.

```
MutableDataHolder OPTIONS = PegdownOptionsAdapter
                    .flexmarkOptions(
                            Extensions.ALL - (headerLinks ? 0 : Extensions.ANCHORLINKS) - (hardwrap ? 0 : Extensions.HARDWRAPS)
                                    + (allowHtml ? 0 : Extensions.SUPPRESS_ALL_HTML), new ConfluenceWikiLinkRenderer(xhtmlContent, info),
                            TaskListExtension.create()).toMutable().set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX, "");
```
So I tried removing **ConfluenceWikiLinkRenderer**  for testing and just passing **TaskListExtension** that did not work out. I am I missing something to work ?

And how I can keep both of them together and need them work without any dependency?

Let me know if anything is not clear.

Thanks
RK

**Comment by rkanumola** [comment] 2017-09-04 11:19
@vsch , did you get a chance to look into the last comment?

**Comment by vsch** [comment] 2017-09-04 15:43
@rkanumola, there is an Extensions.TASKLISTITEMS flag to enable the task list extension using pegdown. 

However, if you are not getting the input check box when parsing and rendering `- [ ] item` then you don't have the task list extension enabled.

The resolving of `[x]` reference is a secondary issue. If the task list items are being parsed then the code will never see `[x]` as a reference because it will be part of the task item node.

The custom renderer would also not be involved unless you are also rendering task and list items.

I do not have your confluence WikiLinkRenderer so cannot comment specifically but unless you are including `TaskListItem` as a node type that you are rendering I don't see why it would affect task list items.

Please double check that you have task lists extension enabled by parsing the simplest task item `- [ ] item` and seeing what the parser document contains. 

If you are looking for an easy way to dump the text version of the AST you can use `AstCollectingVisitor` from the `flexmark-test-util` module which is used by the test harness to generate the AST for the text case:

        final String astText = new AstCollectingVisitor().collectAndGetAstText(document);

**Comment by rkanumola** [comment] 2017-09-06 07:39
@vsch , Thanks for the response.

Can you brief about _"you don't have the task list extension enabled."_ in the last comment? 

I tried few options like **Extensions.TASKLISTITEMS**

```
MutableDataHolder OPTIONS = PegdownOptionsAdapter
                    .flexmarkOptions(Extensions.TASKLISTITEMS+
                            Extensions.ALL - (headerLinks ? 0 : Extensions.ANCHORLINKS) - (hardwrap ? 0 : Extensions.HARDWRAPS)
                                    + (allowHtml ? 0 : Extensions.SUPPRESS_ALL_HTML), new ConfluenceWikiLinkRenderer(xhtmlContent, info)).toMutable()
                    .set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX, ""); 
```

And **TaskListExtension.create()**

```
MutableDataHolder OPTIONS = PegdownOptionsAdapter
                    .flexmarkOptions(
                            Extensions.ALL - (headerLinks ? 0 : Extensions.ANCHORLINKS) - (hardwrap ? 0 : Extensions.HARDWRAPS)
                                    + (allowHtml ? 0 : Extensions.SUPPRESS_ALL_HTML), new ConfluenceWikiLinkRenderer(xhtmlContent, info),TaskListExtension.create()).toMutable()
                    .set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX, "");
```
But none of them working. Can you give me some samples what I am missing ?



As per your last comment, I am here with attaching the wikilink renderer classes ( attached as the content is somewhat huge) for your reference.

> I do not have your confluence WikiLinkRenderer so cannot comment specifically but unless you are including TaskListItem as a node type that you are rendering I don't see why it would affect task list items.

[ConfluenceWikiLinkRenderer.docx](https://github.com/vsch/flexmark-java/files/1280203/ConfluenceWikiLinkRenderer.docx)

Let me know if anything is not clear.

-Thanks

**Comment by rkanumola** [comment] 2017-09-20 09:42
@vsch , thank you so much for the help and support you are providing so far it's awesome, just like to know that you get a chance to look at my last comment?

**Comment by vsch** [comment] 2017-09-20 17:45
@rkanumola, the issue is caused by something in your configuration or the custom extension code. I cannot debug your code. If you isolate what configuration changes or custom extension is causing the problem it will be easier to diagnose the cause. If it is your custom extension, you can post the the problem code here and I may spot the problem.

I am sorry but I don't have time to go through your internal issue documents. Please isolate the issue to specific flexmark-java feature/module or your custom code and then I can help.

**Comment by rkanumola** [comment] 2017-10-05 11:57
@vsch , sorry for the delay in response. Sure. I will give the data you asked for.

-Thanks

**Comment by rkanumola** [comment] 2017-10-06 10:15
@vsch , I tried adding Extensions.TASKLISTITEMS to the pegdown code before we migrated to flexmark. And for the code which I used below

```
PegDownProcessor pegDownProcessor = new PegDownProcessor(Extensions.ALL - (headerLinks ? 0 : Extensions.ANCHORLINKS)
                - (hardwrap ? 0 : Extensions.HARDWRAPS) + (allowHtml ? 0 : Extensions.SUPPRESS_ALL_HTML) + Extensions.TASKLISTITEMS);
        try {
            processed = pegDownProcessor.markdownToHtml(data, new ConfluenceWikiLinkRenderer(info, xhtmlContent));
            // log.debug("pegdown returned HTML: {}", processed);
        } catch (Exception exception) {
            exception.printStackTrace();
            throw new MacroExecutionException("Conversion of Markdown markup failed: " + exception.toString());
        }
```
For the input

* [x]
* [ ]

Output is coming like below
![screen shot 2017-10-06 at 3 39 30 pm](https://user-images.githubusercontent.com/28949740/31273502-9be0d6e4-aaac-11e7-93c6-ee1d346d0d6f.png)

As we are migrated to flexmark we changed the code as per your instructions mentioned at https://github.com/vsch/flexmark-java/issues/119  like below. And this code is not parsing these tasklist items at all. I added Extensions.TASKLISTITEMS as well, not sure why it is not rendering not even like pegdown parser. More over for [x] input it is converting that to an hyper link as I mentioned in the last comment.

```
try {
            MutableDataHolder OPTIONS = PegdownOptionsAdapter
                    .flexmarkOptions(
                            Extensions.ALL +Extensions.TASKLISTITEMS - (headerLinks ? 0 : Extensions.ANCHORLINKS) - (hardwrap ? 0 : Extensions.HARDWRAPS)
                                    + (allowHtml ? 0 : Extensions.SUPPRESS_ALL_HTML), new ConfluenceWikiLinkRenderer(xhtmlContent, info)).toMutable()
                    .set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX, ""); // Needed for Syntax Highlighting

            final ArrayList<Extension> extensions = new ArrayList<Extension>();
            for (Extension ext : OPTIONS.get(Parser.EXTENSIONS)) {
                extensions.add(ext);
            }

            OPTIONS.set(Parser.EXTENSIONS, extensions);

            Parser parser = Parser.builder(OPTIONS).build();
            final HtmlRenderer RENDERER = HtmlRenderer.builder(OPTIONS).build();

            // use the PARSER to parse and RENDERER to render with flexmark compatibility
            com.vladsch.flexmark.ast.Document document = parser.parse(data);
            processedHtml = RENDERER.render(document);
            log.debug("flexmark returned HTML: {}", processedHtml);
        } catch (Exception exception) {
            exception.printStackTrace();
            throw new MacroExecutionException("Conversion of Markdown markup failed: " + exception.toString());
        }
```

let me know if anything is not clear.

-Thanks

**Comment by vsch** [comment] 2017-10-08 21:23
@rkanumola, you keep providing me the same information over and over again hoping that I can figure out what you are doing wrong.

Please get a co-worker to help you debug your code. I really don't have time to provide java programming and debugging tutorials.

**Closed** 2017-10-08 21:23 UTC
Labels: question

**Comment by rkanumola** [comment] 2017-10-09 02:00
Thanks for the support @vsch . Sure I will work with my colleague.
