### ISSUE TITLE
HTML to markdown and removed nested list

### ISSUE THREAD

**Issue by tchudyk** [vsch/flexmark-java#357] opened 2019-07-21 11:10 UTC
Hello,
I have problem with converting HTML list to markdown. The input HTML probably in not totally correct, but in some cases its returned by Chrome when I use editor in `contenteditable` mode. Problem is with element `2` and its sublist `2.1` - this sublist is not inside `<li>` tag, so it's removed during conversion.

Input:
```
<p>List:</p> 
<ul> 
 <li>1</li> 
 <li>2</li> 
 <ul>
  <li>2.1</li>
 </ul> 
 <li>3</li> 
 <li>4
  <ul> 
   <li>4.1</li> 
  </ul> 
 </li> 
 <li>5</li> 
</ul> 
```
Output:
```
List:

- 1
- 2
- 3
- 4
  - 4.1
- 5
```

Expected output:
```
List:

- 1
- 2
  - 2.1
- 3
- 4
  - 4.1
- 5
```

I use here `0.50.18` version of Flexmark.

My java code for conversion:
```
        MutableDataSet dataSet = new MutableDataSet();
        dataSet.set(FlexmarkHtmlConverter.RENDER_COMMENTS, false);
        dataSet.set(FlexmarkHtmlConverter.SETEXT_HEADINGS, false);
        dataSet.set(FlexmarkHtmlConverter.THEMATIC_BREAK, "---");
        dataSet.set(FlexmarkHtmlConverter.SKIP_CHAR_ESCAPE, true);
        dataSet.set(FlexmarkHtmlConverter.BR_AS_PARA_BREAKS, true);
        dataSet.set(FlexmarkHtmlConverter.LISTS_END_ON_DOUBLE_BLANK, false);
        dataSet.set(FlexmarkHtmlConverter.UNORDERED_LIST_DELIMITER, '-');
        dataSet.set(FlexmarkHtmlConverter.LIST_CONTENT_INDENT, true);
        dataSet.set(FlexmarkHtmlConverter.NBSP_TEXT, " ");
        dataSet.set(FlexmarkHtmlConverter.PRE_CODE_PRESERVE_EMPHASIS, false);
        dataSet.set(FlexmarkHtmlConverter.OUTPUT_UNKNOWN_TAGS, true);

        parser = FlexmarkHtmlConverter.builder(dataSet).build();

        return parser.convert(input);
```
The biggest problem is that I lose content typed by user (It would be a smaller problem when it would be returned with incorrect formatting or unescaped html tags). Bonus question - maybe is there any possibility to create some "content protection mode"?

**Comment by vsch** [comment] 2019-07-21 11:19
@tchudyk, the issue is the nested `ul` tag which is not inside `li` tag.

I will see if I can add parsing of these as if they are part of previous item. It will not work if there is no previous item. In which case the nested list will be treated as part of the first list.

```html
<p>List:</p> 
<ul> 
 <ul>
  <li>2.1</li>
 </ul> 
 <li>1</li> 
 <li>2</li> 
 <li>3</li> 
 <li>4
  <ul> 
   <li>4.1</li> 
  </ul> 
 </li> 
 <li>5</li> 
</ul>
```
 
Will result in:

```markdown
- 2.1
- 1
- 2
- 3
- 4
  - 4.1
- 5
```

**Comment by vsch** [comment] 2019-07-21 13:16
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by tchudyk** [comment] 2019-07-21 13:19
It's not perfect, but always better then losing data.

**Comment by vsch** [comment] 2019-07-21 13:32
@tchudyk, nested list before the first list item works in HTML but markdown does not have syntax to allow for this. 

Another way of handling this would be to create an empty first item:

```markdown
-
  - 2.1
- 1
- 2
- 3
- 4
  - 4.1
- 5
```

Which is not ideal either. Such is life with compromises.

**Comment by tchudyk** [comment] 2019-07-21 14:42
I've also fixed it on my site, by putting this kind of "abandoned" `ul` to last found `li` using regexp - maybe this will be helpful for someone.

```
Pattern.compile("</li>\\s*<ul>(.*?)</ul>", Pattern.DOTALL)
                .matcher(input).replaceAll("<ul>$1</ul></li>");
```
(This will not work when nested ul is first element on list).

**Closed** 2020-02-09 21:26 UTC
Labels: :fire: enhancement, :tada: fixed
