### ISSUE TITLE
Bad markup prevents markdown from being processed

### ISSUE THREAD

**Issue by krichards** [vsch/flexmark-java#167] opened 2017-10-26 15:48 UTC
We are looking to move away from PegDown as we have been bitten by a bug where certain markdown causes our application to generate a page in 30 minutes instead of the normal milliseconds.

We've started by using this setup with flexmark:

    private static final DataHolder OPTIONS = flexmarkOptions(true, NONE)
    private static final Parser PARSER = Parser.builder(OPTIONS).build()
    private static final HtmlRenderer RENDERER = HtmlRenderer.builder(OPTIONS).build()

However we have found that when markdown is wrapped in some invalid markup it doesn't get processed, whereas it did with PegDown.  For example this:

`<div align=center><br> [iBooks](https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewFeature?id=1042438110&app=itunes&at=1000l8cU&ct=shoptobrstore)<br>`

no longer generates anchor links.  Any suggestions on how to get  flexmark to match pegdown and be more tolerant to bad markup?

**Comment by pm-fawkes** [comment] 2017-10-27 14:43
Actually  there seem to be other circumstances in which having markup in the markdown breaks processing. e.g " <p>\n [iBooks](https://itunes.apple.com)<br><p>something"

**Comment by vsch** [comment] 2017-10-28 00:42
@krichards, the issue is not bad markup but difference in how pegdown and CommonMark handle HTML.

CommonMark starts an HTML block when it sees an HTML block tag like `<div>` in this case. Like pegdown HTML blocks are not parsed for markdown but passed through. Also, commonmark terminates an HTML block on a blank line while pegdown looks for the closing tag. So if you add a blank line between HTML and markdown then markdown will be parsed for its delimiters. This makes commonmark more flexible in having block HTML tags enclose markdown.

Unlike pegdown, commonmark does not parse the HTML so where pegdown would not find a closing `</div>` tag and would treat the HTML as inline, commonmark treats the whole block as an HTML block and does not parse it for markdown inline constructs.

You can try the strict HTML compatibility mode which parses the HTML for better pegdown compatibility, not perfect but better. https://github.com/vsch/flexmark-java/wiki/Pegdown-Migration#strict-pegdown-html-parsing-mode

**Comment by pm-fawkes** [comment] 2017-10-30 09:20
Hmm... I thought I was using strict? (note: I am using the **PegdownOptionsAdapter**)

> private static final DataHolder OPTIONS = flexmarkOptions(true, NONE)

Thanks anyway - I think we just need to put blank lines in place.  I've managed to go through our content and identify the few areas which aren't right.  Any other tips?

**Comment by pm-fawkes** [comment] 2017-10-30 10:00
Hmm seems like if I turned off strict mode then I get something more like Pegdown used to give me. For instance

```
## We're sorry for any inconvenience.

<div align=center>
<br>

However, you can continue to [explore](/explore-the-story) 
```
This is processed with Pegdown - but from what you said you would not expect it to be.

**Closed** 2018-01-07 00:49 UTC
