### ISSUE TITLE
Autolinks get cut off if they contain `&amp;` (escaped query params)

### ISSUE THREAD

**Issue by andersHj** [vsch/flexmark-java#398] opened 2020-04-17 20:39 UTC
Hi, 

Given this input:
`https://example.com?first=hi&amp;second=hello`

Flexmark gives this output:
`<p><a href="https://example.com?first=hi">https://example.com?first=hi</a>&amp;second=hello</p>`

So the generated link will be cut off before the &amp; part and hence not contain the second query parameter.

This might be intended? But it works in Pegdown which will return:
`<p><a href="https://example.com?first=hi&amp;second=hello" target="_blank">https://example.com?first=hi&amp;second=hello</a></p>`

![image](https://user-images.githubusercontent.com/2843210/79610320-9b104180-80f8-11ea-80be-53b650f82dd6.png)

(The reason I get this `&amp;` in the url in the first place is that I escape the input to the parser.)

## Example code: (Flexmark version: 0.61.10)
```
import org.apache.commons.lang3.StringEscapeUtils;

import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.profile.pegdown.Extensions;
import com.vladsch.flexmark.profile.pegdown.PegdownOptionsAdapter;
import com.vladsch.flexmark.util.data.DataHolder;

public class MarkdownParserBase {
    private final static int PEGDOWN_EXTENSIONS =  Extensions.AUTOLINKS;

    private static final DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
        PEGDOWN_EXTENSIONS
    );

    public static Parser PARSER = Parser.builder(OPTIONS).build();
    public static HtmlRenderer htmlRenderer = HtmlRenderer.builder(OPTIONS).build();
    
    public static String getEscapedHtml(String markdownString) {
        String escapedDescription = StringEscapeUtils.escapeHtml4(markdownString);
        return htmlRenderer.render(PARSER.parse(escapedDescription));
    }

    public static void main(String[] args) {
        String input = "An auto-link: https://example.com?first=hi&second=hello";
        System.out.println(MarkdownParserBase.getEscapedHtml(input));
        // Prints :
        // <p>An auto-link: <a href="https://example.com?first=hi">https://example.com?first=hi</a>&amp;second=hello</p>
    }
}
```

**Comment by vsch** [comment] 2020-04-17 21:49
@andersHj, pegdown does its own auto-link parsing along with everything else. 

Flexmark uses org.nibor.autolink in a post-processor which scans AST for autolinks. 

I missed adding `HtmlEntity` nodes to be appended to text when they follow immediately after.

I now added the code to handle them.

Escaping all markdown will cause the autolinks to have `&amp;` in the link text. The URL will be correct since HTML entities are converted, but the text will have the `&` of `&amp;` converted to HTML Entity. This is the expected behaviour since the link text will have `&` escaped.

You will get: https://example.com/?first=hi&amp;second=hello not https://example.com/?first=hi&second=hello

Pegdown, does not convert link text to HTML entities.

Here is the spec test case for this condition:

```````````````````````````````` example Issues - xxx.4: 1
https://example.com/?first=hi&amp;second=hello
.
<p><a href="https://example.com/?first=hi&amp;second=hello">https://example.com/?first=hi&amp;amp;second=hello</a></p>
.
Document[0, 46]
  Paragraph[0, 46]
    TextBase[0, 46] chars:[0, 46, "https … hello"]
      AutoLink[0, 46] text:[0, 46, "https://example.com/?first=hi&amp;second=hello"] pageRef:[0, 46, "https://example.com/?first=hi&amp;second=hello"]
        Text[0, 46] chars:[0, 46, "https … hello"]
````````````````````````````````

**Comment by vsch** [comment] 2020-04-18 02:40
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by vsch** [comment] 2020-04-18 19:37
@andersHj, I missed adding a test with multiple HTML entities in the auto-link. Now fixed and new release on its way.

```````````````````````````````` example Issues - 398: 2
https://example.com/?first=hi&amp;second=hello&amp;third=ok
.
<p><a href="https://example.com/?first=hi&amp;second=hello&amp;third=ok">https://example.com/?first=hi&amp;amp;second=hello&amp;amp;third=ok</a></p>
.
Document[0, 59]
  Paragraph[0, 59]
    TextBase[0, 59] chars:[0, 59, "https … rd=ok"]
      AutoLink[0, 59] text:[0, 59, "https://example.com/?first=hi&amp;second=hello&amp;third=ok"] pageRef:[0, 59, "https://example.com/?first=hi&amp;second=hello&amp;third=ok"]
        Text[0, 59] chars:[0, 59, "https … rd=ok"]
````````````````````````````````

**Comment by vsch** [comment] 2020-04-18 19:40
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by andersHj** [comment] 2020-04-20 07:36
Thanks a lot for quick fix! Seems to work fine. 👍

**Closed** 2021-08-31 17:38 UTC
Labels: :beetle: bug, :potable_water: fix available, :tada: fixed
