### ISSUE TITLE
Issue with indented (>4 whitespaces) nested HTML code

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#100] opened 2017-05-10 14:14 UTC
I could not really find an option that enables flexmark to parse the following example as HTML, including the nested indented `<div>`-tags. Indented code blocks still need to be supported (I've enabled almost all pegdown extensions using the adapter).

```
<div>
  <div>

    <div>nested-2-levels</div>

    <div>nested-2-levels</div>
  
  </div>
</div>
```

It eventually renders it as div elem but with a code block within:

```
<div>
<pre><code>&lt;div&gt;nested-2-levels&lt;/div&gt;

&lt;div&gt;nested-2-levels&lt;/div&gt;
</code></pre>
  </div>
```

Pegdown rendered this without parsing the nested div as indented code blocks. Any suggestions?

**Comment by vsch** [comment] 2017-05-11 13:36
@Elmervc, this is caused by the CommonMark spec ending an HTML block on a blank line not on a closing tag.

I would have to add an option to not end an HTML block on a blank line but continue to the closing tag.

If you remove the blank lines then it will parse as a single HTML block.

**Comment by Elmervc** [comment] 2017-05-11 13:57
@vsch Thanks. I understand that removing the blank lines fixes it. However it's hard to scan all user-entered content in our system for this issue. For now I understand there's no easy fix to leave the parser in HTML context after blank lines.

**Comment by vsch** [comment] 2017-05-11 13:58
@Elmervc, leaving the parser in the HTML block is not necessarily hard. I just have to add the option and implement the code and tests to handle this.

I will work on it today and should be able to make a release as soon as it is done. I will let you know when it is complete.

**Comment by Elmervc** [comment] 2017-05-11 14:01
@vsch 👍 +1 again for solving issues/adding features so quickly

**Comment by vsch** [comment] 2017-05-12 23:12
@Elmervc, this will take a bit more effort than I anticipated because the HTML block tags are not processed for matching close tag.

Pegdown did not have this issue because it parsed everything in one step. This however caused all the other pegdown issues including slow performance and exponential parse times.

I forgot that the CommonMark HTML block parser does not do this and only relies on the leading text to be an opening or closing tag to determine if the line is part of the HTML block.

Implementing this option requires that I implement keeping track of when the opening block tag is closed by parsing the full line text. I have to implement a stack of open HTML tags so that blank lines in block tags are ignored.

**Comment by Elmervc** [comment] 2017-05-15 12:32
I see. For now I'm scanning more user-entered content for this (and other) issues. Will keep an eye on this one.

**Comment by vsch** [comment] 2017-05-16 14:37
@Elmervc, FYI, some details of CommonMark HTML block parsing.

commonmark-java HTML processing only checks a match at the start of line for various patterns and does not parse the full block. This has more unexpected differences. For example cdata tag will be parsed to its closing tag only when cdata is the first element in the block and on the line.

I consider the HTML parsing a bug in the implementation and missing from the CommonMark spec.

HTML block parsing, error only detects `<div>` and not the `<![CDATA[` following it

```````````````````````````````` example Issue 101: 5
<div><![CDATA[
    <div xmlns="http://www.w3.org/1999/html">
    
    </div>
    ]]></div>
.
<div><![CDATA[
    <div xmlns="http://www.w3.org/1999/html">
<pre><code>&lt;/div&gt;
]]&gt;&lt;/div&gt;
</code></pre>
.
Document[0, 91]
  HtmlBlock[0, 61]
  IndentedCodeBlock[70, 91]
````````````````````````````````


If `<![CDATA[` is the first element of an HTML block then it will be parsed correctly.

```````````````````````````````` example Issue 101: 6
<![CDATA[
    <div xmlns="http://www.w3.org/1999/html">
    
    </div>
]]>
.
<![CDATA[
    <div xmlns="http://www.w3.org/1999/html">
    
    </div>
]]>
.
Document[0, 76]
  HtmlBlock[0, 76]
````````````````````````````````

To fix this I am writing an HTML parser that can incrementally parse the HTML for block tags as the block lines are included. It will not be used for inline HTML parsing which happens after blocks are parsed. However, it will allow the HTML parser to properly handle nested block tags and allow blank lines to be included in these. The goal is to have minimal impact of this implementation by only parsing the HTML when the option to parse HTML is enabled and when a blank line is encountered. Additionally, state of parsing up to the last blank line will be stored and only newly added lines to the block will be parsed. This will not handle blank lines embedded in HTML tags like `<div attr="attr"\n\n>` but this should be an acceptable limitation.

**Comment by Elmervc** [comment] 2017-06-06 11:38
@vsch Cool! I think the strategy of parsing the HTML-blocks incrementally will be valuable for more users who migrate to flexmark, as there are many more markdown parsers that do this (see [here](https://johnmacfarlane.net/babelmark2/?text=%3Cdiv%3E%0A++%3Cdiv%3E%0A%0A++++%3Cdiv%3Enested-2-levels%3C%2Fdiv%3E%0A%0A++++%3Cdiv%3Enested-2-levels%3C%2Fdiv%3E%0A++%0A++%3C%2Fdiv%3E%0A%3C%2Fdiv%3E)).

**Comment by vsch** [comment] 2017-07-12 22:53
@Elmervc, release 0.22.2 has this working in pegdown compatibility mode.

**Comment by Elmervc** [comment] 2017-07-13 08:21
@vsch Awesome 👍 , that's 4 issues fixed in a row.
I have just updated our pom file to use 22.2 and tested it to scan for some known migration issues. There seems to be some regressions (or new issues) with this update. I'll post them in a new issue.

**Closed** 2017-07-14 19:59 UTC
Labels: bug, enhancement, fixed :)
