### ISSUE TITLE
FlexmarkHtmlParser produces extra empty list item for eclosing </p> element

### ISSUE THREAD

**Issue by eduard-netsajev** [vsch/flexmark-java#299] opened 2019-01-18 13:29 UTC
Please provide as much information about where the but is located or what you were using:
* [x] `Parser`

Paragraph ending is interpreted as list item. Code with example html:

```
    val htmlParser = FlexmarkHtmlParser.build()
    val mdWriter = MarkdownWriter(StringBuilder())
    val s = """
               <p><b>Note:</b>
               <li>First note.</li>
               <li>Second note.</li>
               </p>"""
    htmlParser.parse(mdWriter, s)
```

**Expected behavior**
The parser produces a list of 2 items, it does not produce a list item for enclosing `</p>` tag

**Resulting Output**
The result contains extra empty list item.
```
**Note:**
* First note.
* Second note.
*  

```

**Additional context**
Would be nice to have an option to turn off parsing `<p>` tags as list items via parser options. Or any other option so that the example input produces valid markdown text.

The code that botches the output in question lies here:
https://github.com/vsch/flexmark-java/blob/c9da145a062ce052e21db97c9f406fa5c42c5469/flexmark-html-parser/src/main/java/com/vladsch/flexmark/convert/html/FlexmarkHtmlParser.java#L1311

**Comment by vsch** [comment] 2019-01-18 13:55
@eduard-netsajev, thank you for catching this. The error is caused by empty p tag which jsoup creates from the closing p tag.

I added a test to ignore empty p tags.

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Closed** 2019-02-23 17:02 UTC
Labels: :beetle: bug, :potable_water: fix available, :tada: fixed
