### ISSUE TITLE
Link text inline content fails to parse image references

### ISSUE THREAD

**Issue by jingibus** [vsch/flexmark-java#407] opened 2020-04-29 18:32 UTC
The CommonMark spec says that link text may itself contain inline content. Example 525:

```
[![moon](moon.jpg)](/uri)
```
yields:
```
<p><a href="/uri"><img src="moon.jpg" alt="moon" /></a></p>
```

In FlexMark, however, inline content that consists of an image reference fails to parse and is passed straight through as the link text. Example test case:

```
[![][moon]](/uri)

[moon]: moon.jpg
```
yields:
```
<p><a href=\"/uri\">![][moon]</a></p>
```

The expected output is:
```
<p><a href="/uri"><img src="moon.jpg" alt="moon" /></a></p>
```

Verified with `ParserEmulationProfile.COMMONMARK_0_28` and `ParserEmulationProfile.MULTI_MARKDOWN`.

Additional context:
My application uses `ParserEmulationProfile.MULTI_MARKDOWN`. MultiMarkdown uses image references to encode width/height data, which I am reliant on. So this is a hard blocker for me that I will need to work around in one way or another.

**Comment by vsch** [comment] 2020-04-29 20:34
@jingibus, thank you for catching it. I can confirm it is a bug. Will release fix shortly.

**Comment by vsch** [comment] 2020-04-29 20:37
@jingibus, btw, the expected output in your case would be:

    <p><a href="/uri"><img src="moon.jpg" alt="" /></a></p>

the alt is empty because you are using syntax `[![alt text][moon]](/uri)`, which overrides the default alt with one which is empty. Use `[![moon]](/uri)` or `[![moon][]](/uri)` to use the reference id as alt text.

**Comment by vsch** [comment] 2020-04-29 20:42
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by vsch** [comment] 2020-04-29 22:35
@jingibus, had to make another release `0.61.24` to handle reference links in link text. This does not affect reference images but does cause issues with CommonMark reference implementation compatibility.

**Comment by jingibus** [comment] 2020-04-29 23:03
Unbelievable. Thank you so much!

I've got a followup that's specific to MultiMarkdown coming, but I've confirmed the issue reported here is fixed on my end.

**Closed** 2020-04-29 23:04 UTC
Labels: :beetle: bug, :potable_water: fix available, :tada: fixed
